### ISSUE TITLE
Invalid Scopes: read_stream error when signing into Facebook on the demo

### ISSUE THREAD

**Issue by cnorval** [uoscompsci/PRISONER#4]
Whenever I try to log into Facebook during the prisoner-demo, I receive the following error message:

> 
Error
Invalid Scopes: read_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

Continuing past this window, I am taken to a page with the following error:

> ValueError
ValueError: No JSON object could be decoded

Traceback:
https://gist.github.com/anonymous/b39f29ae414ed54236f137b0e0ece10c

**Comment by barneyboo** [comment]
This may be fixed in c74cdd81a3b62f8aaaf49fe448d846777dbd6b56. Please let me know if this is still broken, thanks!

**Comment by cnorval** [comment]
This issue appears to be fixed. Tested on the prisoner-demo docker image.
