### ISSUE TITLE
Demo error after authorising Twitter app

### ISSUE THREAD

**Issue by cnorval** [uoscompsci/PRISONER#5]
I have changed the `/usr/bin/prisoner-demo/demo.py` line to `SOCIAL_NETWORK = "Twitter"`. After authorising with the application, I get redirected to the following error message:

> jinja2.exceptions.TemplateSyntaxError
TemplateSyntaxError: Encountered unknown tag 'elseif'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.

Traceback:
https://gist.github.com/anonymous/8b20a7ef3c2396baecd64b0f2851dc8b

**Comment by barneyboo** [comment]
This should be fixed in 1263dc0dae68924c2cb32a8c500e95753151a404. Please let me know if there's still an issue with this, thanks!

**Comment by cnorval** [comment]
This issue appears to be fixed. Tested on the prisoner-demo docker image.
